language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq expect
  - git clone https://github.com/sstephenson/bats.git
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
before_script:
  - export PATH=$PATH:$PWD
script: bats/bin/bats --tap tests/
notifications:
  email:
    on_success: never
env:
- SKIP_SUDO_TESTS=1
